 goal: makefile.dep
	make autocorrelation.x
	make franck_condon.x
	make pe_spectrum.x

MAKEFLAGS = -r

.SUFFIXES: .f90 .o .x .c .dep

#
# System-specific overrides
#

include configs/volk-64opt.mak
# include configs/volk-64dbg.mak

#
# Finish the set-up
#
LIBS = $(LAPACK) $(FFTW3) $(DXLIB)

#
# Compiling and archiving rules
#
.f90.o:
	$(F90) -c $<

dgefa.o:	dgefa.f
	$(F90) -c dgefa.f

dgedi.o:	dgedi.f
	$(F90) -c dgedi.f

.c.o:
	$(CC) -c $<

clean:
	-/bin/rm -f *.{o,mod,x,il,a} checkpoint_{field,main}.* makefile.dep

makefile.dep: $(shell echo *.f90)
	../make-depend.sh $^ > $@

#
# Explicit dependencies
#

LIBFC += accuracy.o
LIBFC += cache_fc.o
LIBFC += cache_gr.o
LIBFC += dgedi.o
LIBFC += dgefa.o
LIBFC += elements.o
LIBFC += fc_tools.o
LIBFC += lapack.o
LIBFC += math.o
LIBFC += timer.o

#
# Building the binaries
#
autocorrelation.x: autocorrelation.o $(LIBFC)
	$(F90) -o autocorrelation.x autocorrelation.o $(LIBFC) $(LIBS)

franck_condon.x: franck_condon.o $(LIBFC)
	$(F90) -o franck_condon.x franck_condon.o $(LIBFC) $(LIBS)

pe_spectrum.x: pe_spectrum.o $(LIBFC)
	$(F90) -o pe_spectrum.x pe_spectrum.o $(LIBFC) $(LIBS)

#
# Automatically-generated dependencies
#
include makefile.dep

